export const Auth = {
  CLEAR_LOGIN_FIELDS: 'auth/CLEAR_LOGIN_FIELDS',
  USER_LOADED: 'auth/USER_LOADED',
  LOG_OUT: 'auth/LOG_OUT',
  WALK_THROUGH: 'auth/WALKTHROUGH',
  LOGIN_USER_ATTEMPT: 'auth/LOGIN_USER_ATTEMPT',
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',
};
